### ISSUE TITLE
Where is the source code of the admm binary?

### ISSUE THREAD

**Issue by michalrus** [unattended-ch/admm#8]
I'm quite confused, where is the source code of the admm binary that’s being published in the releases?

**Comment by unattended-ch** [comment]
It's my private project, so no source code only binarys.
The work is anyway almost done by the scripts.

**Comment by michalrus** [comment]
I'm sorry, but this is very suspicious. I can only assume that the binary contains backdoors/other malware.

**Comment by unattended-ch** [comment]
Can you prove that ?
Or is that just your trick.
